export default ALL_PRODUCTS_REQUEST = "ALL_PRODUCT_REQUEST";
export default ALL_PRODUCTS_SUCCESS = "ALL_PRODUCT_SUCCESS";
export default ALL_PRODUCTS_FAIL = "ALL_PRODUCT_FAIL";

export default CLEAR_ERRORS = "CLEAR_ERRORS";
